/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MyCard: typeof import('./src/components/common/MyCard.vue')['default']
    MyMenu: typeof import('./src/components/MyMenu.vue')['default']
    MyModel: typeof import('./src/components/common/MyModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisitRoute: typeof import('./src/components/VisitRoute.vue')['default']
  }
}
